import { Lang } from "../models/lang";

export const enEN: Lang = {
    "home_title": "My Project Manager" ,
    "home_slogan": "Where your ideas find their way.",
    "home_register": "Create Account",
    "home_login": "Login",
    "home_create_projects": "Create projects",
    "home_create_team_project_tool": "Create a team project with this project management tool.",
    "home_create_several_projects": "Create several projects at once.",
    "home_create_activities": "Create activities for each of your projects.",
    "home_modify_project": "Modify your project",
    "home_make_changes_modify_project": "Make changes to modify your project.",
    "home_add_remove_members": "Add and remove Members",
    "home_add_remove_project_members": "You can add or remove your project members.",
    "home_change_activity_elements": "Changes activity elements",
    "home_edit_activity_elements": "You can edit elements of your activities in a simple way.",
    "footer_about_us": "About Us",
    "footer_back_to_up": "Back to top",
    "projects": "Projects",
    "activities": "Activities",
    "pather_home": "Home",
    "pather_projects": "Projects",
    "pather_all": "All",
    "pather_unassigned": "Unassigned",
    "pather_in_progress": "In progress",
    "pather_completed": "Completed",
    "pather_pause": "Pause",
    "pather_members": "Members",
    "pather_add": "Add",
    "pather_information": "Information",
    "pather_profile": "Profile",
    "pather_security": "Security",
    "pather_sitemap": "Site Map",
    "pather_privacy": "Privacy Policy",
    "pather_error": "Error",
    "projects_create": "Create",
    "projects_search": "Search projects...",
    "login": "Login",
    "register": "Register",
    "account": "Account",
    "logout": "Logout",
    "account_settings": "Account settings",
    "themes": "Themes",
    "icons": "Icons",
    "change_theme": "Are you sure you want to change the theme?",
    "change_icon": "Are you sure you want to change the icon?",
    "action_cancel": "Cancel",
    "action_save_changes": "Save changes",
    "action_update": "Update",
    "action_submit": "Submit",
    "user_name": "User name",
    "email_address": "Email address",
    "phone": "Phone",
    "password": "Password",
    "new_user_name": "Confirm new user name",
    "new_email": "Confirm new email address",
    "new_phone": "Confirm new Telephone",
    "new_password": "Confirm new password",
    "change_user_name": "Confirm user name change",
    "change_email_address": "Confirm email change",
    "change_phone": "Confirm Telephone change",
    "change_password": "Confirm password change",
    "phone_number": "Telephone number",
    "remember": "Remember me",
    "user_validation_messages": {
        "minlength": "The number of characters is minimum 5 and maximum 15.",
        "pattern": "You can only use letters and numbers for your username.",
        "minlength_pattern": "The number of characters minimum is 5 and maximum 15 and you can only use letters and numbers for your username.",
        "matchfields": "The names do not match."
    },
    "email_validation_message": {
        "email": "Not a valid email address.",
        "matchfields": "The emails do not match."
    },
    "phone_validation_messages": {
        "minlength": "The number of characters does not match.",
        "pattern": "Not a valid number.",
        "minlength_pattern": "The number of characters does not match and is not a valid number.",
        "matchfields": "The phone numbers do not match."
    },
    "password_validation_messages": {
        "minlength": "The password is invalid. The minimum number of characters is 6.",
        "pattern": "The password is invalid. It must contain at least one number, two letters and must not contain commas, quotation marks, braces, brackets, or blank spaces.",
        "minlength_pattern": "The password is invalid. The minimum number of characters is 6, it must contain at least one number, two letters and must not contain commas, quotation marks, braces, brackets, or blank spaces.",
        "matchfields": "Passwords do not match."
    },
    "loading": "Loading...",
    "error_message": "Oops! Something went wrong.",
    "back_to_home": "Back to Home",
    "activities_search": "Search activities...",
    "members_search": "Search members...",
    "options": "Options",
    "password_lost": "Forgot your password?",
    "password_recovery": {
        "text": "Password recovery",
        "request": "Password recovery - Request",
        "reset": "Password recovery - Reset "
    },
    "submit": "Submit",
    "verify_account": "Verify account",
    "verify_status": {
        "completed": "Verified account",
        "error": "Error verifying account",
        "inprocess": "Verifying account"
    },
    "verify_email": "Verify e-mail",
    "verified": "Verified",
    "project_options": "Project options",
    "change_project_name": "Change project name",
    "change_description": "Change description",
    "start_date": "Start date",
    "completion_date": "Completion date",
    "actual_date": "Actual date",
    "create_project": "Create project",
    "project_name": "Project name",
    "project_description": "Project description",
    "add_activity": "Add activity",
    "activity_name": "Activity name",
    "description_activity": "Description activity",
    "status": "Status",
    "participating_roles": "Participating roles",
    "analyst": "Analyst",
    "designer": "Designer",
    "programmer": "Programmer",
    "leader": "Leader",
    "change_activity_name": "Change activity name",
    "change_status": "Change status",
    "enter": "Enter",
    "select_rol": "Select role",
    "member": "Member",
    "remove": "Remove",
    "change_rol": "Change role",
    "update_member": "Update member",


    "mpm_description_1": "MPM offers a complete solution for project management, especially designed for development teams.",
    "mpm_description_2": "MPM provides an intuitive and easy-to-use interface to efficiently manage all stages of projects.",
    "mpm_description_3": "MPM classifies tasks into categories such as assigned, in progress, completed and paused, making it easy to track project progress.",
    "mpm_description_4": "MPM assigns clear roles to each team member (project leader, analyst, designer, developer), ensuring that everyone understands their specific responsibilities.",
    "mpm_description_5": "MPM simplifies project management for development teams, offering:",
    "mpm_description_6": "Intuitive and easy-to-use interface to manage all stages of projects efficiently.",
    "mpm_description_7": "Classification of tasks into categories such as assigned, in progress, completed and paused for accurate tracking of project progress.",
    "mpm_description_8": "Clear assignment of roles to each team member (project leader, analyst, designer, developer), ensuring a complete understanding of specific responsibilities.",
    "tag_error": "Your browser does not support HTML5 videos.",
    "strong_1": "Simplify complexity:",
    "strong_2": "Task visualization system:",
    "strong_3": "Detailed role system:",
    "toast": {
        "register_ok": "Successfully registered",
        "register_error": "Bad Request",
        "login_error": "Incorrect data",
        "project_add_ok": "Project successfully created",
        "project_add_error": "Error creating the project",
        "activity_add_ok": "The activity was added",
        "activity_add_error": "Error adding activity",
        "member_add_ok": "Member added",
        "member_add_error": "Error adding a member",
        "verify_accont_ok": "Verification email sent",
        "verify_accont_error": "Server error",
        "recovery_email_ok": "Recovery email sent",
        "update_ok": "Successfully updated",
        "update_error": "Error updating",
        "delete_ok": "Correctly eliminated",
        "delete_error": "Error when deleting",
        "status_cancel": "Operation Canceled",
        "status_complited": "Operation Completed",
        "capcha": "Complete the captcha",
    }
}

export const esMX: Lang = {
    "home_title": "My Project Manager"/*"Mi Gerente de Proyectos"*/,
    "home_slogan": "Donde tus ideas encuentran su camino.",
    "home_register": "Crear una cuenta",
    "home_login": "Iniciar sesión",
    "home_create_projects": "Crear proyectos",
    "home_create_team_project_tool": "Crea un proyecto de equipo con esta herramienta de gestión de proyectos.",
    "home_create_several_projects": "Crea varios proyectos a la vez.",
    "home_create_activities": "Crea actividades para cada uno de tus proyectos.",
    "home_modify_project": "Modifica tu proyecto",
    "home_make_changes_modify_project": "Realiza cambios para modificar tu proyecto.",
    "home_add_remove_members": "Agrega y elimina miembros",
    "home_add_remove_project_members": "Puedes agregar o eliminar miembros de tu proyecto.",
    "home_change_activity_elements": "Cambia elementos de la actividad",
    "home_edit_activity_elements": "Puedes editar elementos de tus actividades de manera sencilla.",
    "footer_about_us": "¿Quiénes Somos?",
    "footer_back_to_up": "Volver arriba",
    "projects": "Proyectos",
    "activities": "Actividades",
    "pather_home": "Inicio",
    "pather_projects": "Proyectos",
    "pather_all": "Todas",
    "pather_unassigned": "No asignadas",
    "pather_in_progress": "En progreso",
    "pather_completed": "Completadas",
    "pather_pause": "Pausa",
    "pather_members": "Miembros",
    "pather_add": "Agregar",
    "pather_information": "Información",
    "pather_profile": "Perfil",
    "pather_security": "Seguridad",
    "pather_sitemap": "Mapa del sitio",
    "pather_privacy": "Política de privacidad",
    "pather_error": "Error",
    "projects_create": "Crear",
    "projects_search": "Buscar proyectos...",
    "login": "Iniciar sesión",
    "register": "Regístrate",
    "account": "Cuenta",
    "logout": "Cierrar sesión",
    "account_settings": "Configuración de la cuenta",
    "themes": "Temas",
    "icons": "Iconos",
    "change_theme": "¿Estás seguro de que quieres cambiar el tema?",
    "change_icon": "¿Seguro que quieres cambiar el icono?",
    "action_cancel": "Cancelar",
    "action_save_changes": "Guardar cambios",
    "action_update": "Actualizar",
    "action_submit": "Enviar",
    "user_name": "Nombre de usuario",
    "email_address": "Correo electrónico",
    "phone": "Teléfono",
    "password": "Contraseña",
    "new_user_name": "Confirmar nuevo nombre de usuario",
    "new_email": "Confirmar nuevo correo electrónico",
    "new_phone": "Confirmar nuevo teléfono",
    "new_password": "Confirmar nuevo contraseña",
    "change_user_name": "Confirmar el cambio de nombre de usuario",
    "change_email_address": "Confirmar el cambio de correo electrónico",
    "change_phone": "Confirmar el cambio de teléfono",
    "change_password": "Confirmar el cambio de contraseña",
    "phone_number": "Número de teléfono",
    "remember": "Recuérdame",
    "user_validation_messages": {
        "minlength": "El número de caracteres es de 5 como mínimo y 15 como máximo.",
        "pattern": "Solo puedes usar letras y números para tu nombre de usuario.",
        "minlength_pattern": "El número de caracteres es de 5 como mínimo y 15 como máximo y solo puedes usar letras y números para tu nombre de usuario.",
        "matchfields": "Los nombres no coinciden."
    },
    "email_validation_message": {
        "email": "Dirección de correo electrónico no válida.",
        "matchfields": "Los correos no coinciden."
    },
    "phone_validation_messages": {
        "minlength": "El número de caracteres no coincide.",
        "pattern": "Número no válido.",
        "minlength_pattern": "El número de caracteres no coincide y no es un número válido.",
        "matchfields": "Los números de teléfono no coinciden."
    },
    "password_validation_messages": {
        "minlength": "La contraseña no es válida. El número de caracteres mínimo es 6.",
        "pattern": "La contraseña no es válida. Debe contener al menos un número, dos letras y no debe contener comas, comillas, llaves, corchetes, o espacios en blanco.",
        "minlength_pattern": "La contraseña no es válida. El número de caracteres mínimo es 6, debe contener al menos un número, dos letras y no debe contener comas, comillas, llaves, corchetes, o espacios en blanco.",
        "matchfields": "Las contraseñas no coinciden."
    },
    "loading": "Cargando...",
    "error_message": "¡Uy! Algo ha salido mal.",
    "back_to_home": "Ir al Inicio",
    "activities_search": "Buscar actividades...",
    "members_search": "Buscar miembros...",
    "options": "Opciones",
    "password_lost": "¿Olvidaste tu contraseña?",
    "password_recovery": {
        "text": "Recuperar contraseña",
        "request": "Recuperar contraseña - Petición",
        "reset": "Recuperar contraseña - Restabler "
    },
    "submit": "Enviar",
    "verify_account": "Verificar cuenta",
    "verify_status": {
        "completed": "Cuenta verificada",
        "error": "Error al verificar la cuenta",
        "inprocess": "Verificando cuenta"
    },
    "verify_email": "Verificar correo electrónico",
    "verified": "Verificado",
    "project_options": "Opciones del proyecto",
    "change_project_name": "Cambiar nombre del proyecto",
    "change_description": "Cambiar descripción",
    "start_date": "Fecha de inicio",
    "completion_date": "Fecha de finalización",
    "actual_date": "Fecha actual",
    "create_project": "Crear proyecto",
    "project_name": "Nombre del proyecto",
    "project_description": "Descripción del proyecto",
    "add_activity": "Agregar actividad",
    "activity_name": "Nombre de la actividad",
    "description_activity": "Descripción de la actividad",
    "status": "Estado",
    "participating_roles": "Roles participantes",
    "analyst": "Analista",
    "designer": "Diseñador",
    "programmer": "Programador",
    "leader": "Líder",
    "change_activity_name": "Cambiar nombre de la actividad",
    "change_status": "Cambiar estado",
    "enter": "Introduzca",
    "select_rol": "Seleccionar rol",
    "member": "Miembro",
    "remove": "Eliminar",
    "change_rol": "Cambiar rol",
    "update_member": "Actualizar miembro",

    
    "mpm_description_1": "MPM ofrece una solución completa para la gestión de proyectos, especialmente diseñada para equipos de desarrollo.",
    "mpm_description_2": "MPM proporciona una interfaz intuitiva y fácil de usar que permite gestionar eficientemente todas las etapas de los proyectos.",
    "mpm_description_3": "MPM clasifica las tareas en categorías como asignadas, en proceso, completadas y pausadas, lo que facilita el seguimiento del avance del proyecto.",
    "mpm_description_4": "MPM asigna roles claros a cada miembro del equipo (líder de proyecto, analista, diseñador, desarrollador), garantizando que todos comprendan sus responsabilidades específicas.",
    "mpm_description_5": "MPM simplifica la gestión de proyectos para equipos de desarrollo, ofreciendo:",
    "mpm_description_6": "Interfaz intuitiva y fácil de usar para gestionar todas las etapas de los proyectos eficientemente.",
    "mpm_description_7": "Clasificación de tareas en categorías como asignadas, en proceso, completadas y pausadas para un seguimiento preciso del avance del proyecto.",
    "mpm_description_8": "Asignación clara de roles a cada miembro del equipo (líder de proyecto, analista, diseñador, desarrollador), garantizando una comprensión completa de las responsabilidades específicas.",
    "tag_error": "Tu navegador no soporta videos HTML5.",
    "strong_1": "Simplifica la complejidad:",
    "strong_2": "Sistema de visualización de tareas:",
    "strong_3": "Sistema de roles detallado:",
    "toast": {
        "register_ok": "Registrado con éxito",
        "register_error": "Bad Request",
        "login_error": "Datos incorrectos",
        "project_add_ok": "Proyecto creado con éxito",
        "project_add_error": "Error al crear el proyecto",
        "activity_add_ok": "La actividad se ha añadido",
        "activity_add_error": "Error al añadir la actividad",
        "member_add_ok": "Miembro añadido",
        "member_add_error": "Error al añadir un miembro",
        "verify_accont_ok": "Correo electrónico de verificación enviado",
        "verify_accont_error": "Error del servidor",
        "recovery_email_ok": "Correo electrónico de recuperación enviado",
        "update_ok": "Actualizado correctamente",
        "update_error": "Error al actualizar",
        "delete_ok": "Eliminado correctamente",
        "delete_error": "Error al eliminar",
        "status_cancel": "Operación cancelada",
        "status_complited": "Operación completada",
        "capcha": "Completa el captcha",
    }
}