import { Lang } from "../models/lang";

export const enEN: Lang = {
    "home_title": 'My Proyect Manager' ,
    "home_slogan": 'Where your ideas find their way.',
    "home_register": 'Create Account',
    "home_login": 'Login',
    "home_create_projects": 'Create projects',
    "home_create_team_project_tool": 'Create a team project with this project management tool.',
    "home_create_several_projects": 'Create several projects at once.',
    "home_create_activities": 'Create activities for each of your projects.',
    "home_modify_project": 'Modify your project',
    "home_make_changes_modify_project": 'Make changes to modify your project.',
    "home_add_remove_members": 'Add and remove Members',
    "home_add_remove_project_members": 'You can add or remove your project members.',
    "home_change_activity_elements": 'Changes activity elements',
    "home_edit_activity_elements": 'You can edit elements of your activities in a simple way.',
    "footer_about_us": "About Us",
    "footer_back_to_up": "Back to top",
    "projects": 'Projects',
    "activities": 'Activities',
    "pather_home": 'Home',
    "pather_projects": 'Projects',
    "pather_all": 'All',
    "pather_unassigned": 'Unassigned',
    "pather_in_progress": 'In progress',
    "pather_completed": 'Completed',
    "pather_pause": 'Pause',
    "pather_members": 'Members',
    "pather_add": 'Add',
    "pather_information": 'Information',
    "pather_profile": 'Profile',
    "pather_security": 'Security',
    "projects_create": 'Create',
    "projects_search": "Search projects...",
    "login": "Login",
    "register": "Register",
    "account": "Account",
    "logout": "Logout",
    "account_settings": "Account settings",
    "themes": "Themes",
    "icons": "Icons",
    "change_theme": "Are you sure you want to change the theme?",
    "change_icon": "Are you sure you want to change the icon?",
    "action_cancel": "Cancel",
    "action_save_changes": "Save changes",
    "action_update": "Update",
    "action_submit": "Submit",
    "user_name": "User name",
    "email_address": "Email address",
    "phone": "Phone",
    "password": "Password",
    "new_user_name": "Confirm new user name",
    "new_email": "Confirm new email address",
    "new_phone": "Confirm new Telephone",
    "new_password": "Confirm new password",
    "change_user_name": "Confirm user name change",
    "change_email_address": "Confirm email change",
    "change_phone": "Confirm Telephone change",
    "change_password": "Confirm password change",
    "phone_number": "Telephone number",
    "remember": "Remember me",
    "user_validation_messages": {
        "minlength": "The number of characters is 5 and maximum 15.",
        "pattern": "You can only use letters and numbers for your username.",
        "minlength_pattern": "The number of characters is 5 and maximum 15 and you can only use letters and numbers for your username."
    },
    "email_validation_message": {
        "email": "Not a valid email address."
    },
    "phone_validation_messages": {
        "minlength": "The number of characters does not match.",
        "pattern": "Not a valid number.",
        "minlength_pattern": "The number of characters does not match and is not a valid number."
    },
    "password_validation_messages": {
        "minlength": "The password is invalid. The number of characters is 6.",
        "pattern": "The password is invalid. It must contain at least one number and must not contain commas, quotation marks, braces, square brackets, or blank spaces.",
        "minlength_pattern": "The password is invalid. The number of characters is 6 and must contain at least one number and must not contain commas, quotation marks, braces, brackets, or blank spaces."
    },
    "loading": "Loading...",
}

export const esMX: Lang = {
    "home_title": 'My Proyect Manager'/*'Mi Gerente de Proyectos'*/,
    "home_slogan": 'Donde tus ideas encuentran su camino.',
    "home_register": 'Crear una cuenta',
    "home_login": 'Iniciar sección',
    "home_create_projects": 'Crear proyectos',
    "home_create_team_project_tool": 'Crea un proyecto de equipo con esta herramienta de gestión de proyectos.',
    "home_create_several_projects": 'Crea varios proyectos a la vez.',
    "home_create_activities": 'Crea actividades para cada uno de tus proyectos.',
    "home_modify_project": 'Modifica tu proyecto',
    "home_make_changes_modify_project": 'Realiza cambios para modificar tu proyecto.',
    "home_add_remove_members": 'Agrega y elimina miembros',
    "home_add_remove_project_members": 'Puedes agregar o eliminar miembros de tu proyecto.',
    "home_change_activity_elements": 'Cambia elementos de la actividad',
    "home_edit_activity_elements": 'Puedes editar elementos de tus actividades de manera sencilla.',
    "footer_about_us": "¿Quiénes Somos?",
    "footer_back_to_up": "Volver arriba",
    "projects": 'Proyectos',
    "activities": 'Actividades',
    "pather_home": 'Inicio',
    "pather_projects": 'Proyectos',
    "pather_all": 'Todos',
    "pather_unassigned": 'No asignados',
    "pather_in_progress": 'En progreso',
    "pather_completed": 'Completados',
    "pather_pause": 'Pausa',
    "pather_members": 'Miembros',
    "pather_add": 'Agregar',
    "pather_information": 'Información',
    "pather_profile": 'Perfil',
    "pather_security": 'Seguridad',
    "projects_create": 'Crear',
    "projects_search": "Buscar proyectos...",
    "login": "Iniciar sesión",
    "register": "Regístrate",
    "account": "Cuenta",
    "logout": "Cierrar sesión",
    "account_settings": "Configuración de la cuenta",
    "themes": "Temas",
    "icons": "Iconos",
    "change_theme": "¿Estás seguro de que quieres cambiar el tema?",
    "change_icon": "¿Seguro que quieres cambiar el icono?",
    "action_cancel": "Cancelar",
    "action_save_changes": "Guardar cambios",
    "action_update": "Actualizar",
    "action_submit": "Enviar",
    "user_name": "Nombre de usuario",
    "email_address": "Correo electrónico",
    "phone": "Teléfono",
    "password": "Contraseña",
    "new_user_name": "Confirmar nuevo nombre de usuario",
    "new_email": "Confirmar nuevo correo electrónico",
    "new_phone": "Confirmar nuevo teléfono",
    "new_password": "Confirmar nuevo contraseña",
    "change_user_name": "Confirmar el cambio de nombre de usuario",
    "change_email_address": "Confirmar el cambio de correo electrónico",
    "change_phone": "Confirmar el cambio de teléfono",
    "change_password": "Confirmar el cambio de contraseña",
    "phone_number": "Número de teléfono",
    "remember": "Recuérdame",
    "user_validation_messages": {
        "minlength": "El número de caracteres es de 5 a 15.",
        "pattern": "Solo puedes usar letras y números para tu nombre de usuario.",
        "minlength_pattern": "El número de caracteres es de 5 a 15 y solo puedes usar letras y números para tu nombre de usuario."
    },
    "email_validation_message": {
        "email": "Dirección de correo electrónico no válida."
    },
    "phone_validation_messages": {
        "minlength": "El número de caracteres no coincide.",
        "pattern": "Número no válido.",
        "minlength_pattern": "El número de caracteres no coincide y no es un número válido."
    },
    "password_validation_messages": {
        "minlength": "La contraseña no es válida. El número de caracteres es 6.",
        "pattern": "La contraseña no es válida. Debe contener al menos un número y no debe contener comas, comillas, llaves, corchetes, o espacios en blanco.",
        "minlength_pattern": "La contraseña no es válida. El número de caracteres es 6 y debe contener al menos un número y no debe contener comas, comillas, llaves, corchetes, o espacios en blanco."
    },
    "loading": "Cargando...",
}